# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'https://rafaelbg27.github.io'
  language: 'us'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-179701210-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Posts', path: 'menu', url: 'posts.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/rafaelbg27'}
- {icon: 'twitter', link: 'https://twitter.com/rafaelbg27'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/rafaelbg27/'}
- {icon: 'medium', link: 'https://medium.com/@rafaelbg27'}

# - {icon: 'envelope', link: 'mailto:rafaelbg270@gmail.com'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
